# Generated by Django 5.0.7 on 2024-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='photo_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_id',
            field=models.IntegerField(null=True),
        ),
    ]
