# Generated by Django 5.0.7 on 2025-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
