# Generated by Django 5.0.7 on 2025-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usersettings_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
