# Generated by Django 5.0.7 on 2024-10-24 21:33

import django.db.models.deletion
import recipes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(default='', max_length=128, null=True)),
                ('barcode', models.CharField(default='', max_length=20, null=True, unique=True)),
                ('quantity', models.FloatField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0, editable=False)),
            ],
            options={
                'db_table': 'nutritions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'units',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
                ('nutrition_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='recipes.nutrition')),
            ],
            options={
                'db_table': 'diaries',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.product')),
            ],
            options={
                'db_table': 'ingredients',
            },
            bases=('recipes.product',),
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], default='breakfast', max_length=20, verbose_name='name')),
                ('count', models.FloatField(default=1)),
                ('count_fractions_in_product', models.PositiveIntegerField(null=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealtimes', to='recipes.diary')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealtimes', to='recipes.product')),
            ],
            options={
                'db_table': 'mealtimes',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.nutrition'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=recipes.models.image_path)),
                ('image_link', models.URLField(blank=True, max_length=512)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.unit'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.product')),
                ('cooking_time_seconds', models.PositiveIntegerField(default=0)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='recipe_ingredients', to='recipes.ingredient')),
            ],
            options={
                'db_table': 'recipes',
            },
            bases=('recipes.product',),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructions/')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.recipe')),
            ],
            options={
                'db_table': 'instructions',
            },
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='only_one_null_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('barcode',), name='unique_barcode'),
        ),
    ]
