# Generated by Django 5.0.7 on 2024-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_barcode',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode',), name='unique_barcode'),
        ),
    ]
