# Generated by Django 5.0.7 on 2024-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_product_unique_barcode_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='tag',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(db_index=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipe_products', to='recipes.product'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=900),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
