# Generated by Django 5.0.7 on 2024-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_productimage_tag_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
