# Generated by Django 5.0.7 on 2024-11-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241123_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=900, unique=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(db_index=True, max_length=900, unique=True),
        ),
    ]
