# Generated by Django 5.0.7 on 2024-11-30 12:35
import os, csv

from django.db import migrations

def load_plants_data(apps, schema_editor):

    Product = apps.get_model('recipes', 'Product')
    Nutrition = apps.get_model('recipes', 'Nutrition')
    Category = apps.get_model('recipes', 'Category')
    Unit = apps.get_model('recipes', 'Unit')

    file_path = os.path.join(os.getcwd(), 'recipes', 'migrations', 'data', 'plants.csv')
    
    with open(file_path, newline='', encoding='windows-1251') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        next(reader)  # Пропуск заголовка
        
        for row in reader:
            category_name, product_name, protein, fat, carbohydrates = row
            
            category, created = Category.objects.get_or_create(name=category_name)

            unit, created = Unit.objects.get_or_create(name="грамм")
            
            nutrition = Nutrition.objects.create(
                protein=float(protein),
                fat=float(fat),
                carbohydrates=float(carbohydrates)
            )
            
            Product.objects.create(
                name=product_name,
                barcode=None,
                category=category,
                nutrition=nutrition,
                data_accepted=True,
                unit=unit,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_product_user'),
    ]

    operations = [
        migrations.RunPython(load_plants_data),
    ]
