# Generated by Django 5.0.7 on 2024-12-26 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models

def create_settings_entry(apps, schema_editor):
    ProjectSettings = apps.get_model('recipes', 'ProjectSettings')
    Unit = apps.get_model('recipes', 'Unit')
    gramm_unit = Unit.objects.filter(models.Q(name__icontains='грамм')|models.Q(synonyms__icontains='грамм'))[0]
    ProjectSettings.objects.create(default_unit=gramm_unit)
    
def remove_settings_entry(apps, schema_editor):
    ProjectSettings = apps.get_model('recipes', 'ProjectSettings')
    ProjectSettings.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20241130_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_settings', to='recipes.unit')),
            ],
            options={
                'db_table': 'project_settings',
                'abstract': False,
            },
        ),
        migrations.RunPython(create_settings_entry, remove_settings_entry)
    ]
