# Generated by Django 5.0.7 on 2025-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет порядка выдачи'),
        ),
    ]
