# Generated by Django 5.0.7 on 2025-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='text_of_the_agreement',
            field=models.TextField(null=True, verbose_name='Текст соглашения'),
        ),
    ]
