# Generated by Django 5.0.7 on 2025-01-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_projectsettings_text_of_the_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info_owner',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Владелец информации о продукте'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_settings', to='recipes.unit', verbose_name='Единица измерения по умолчанию'),
        ),
    ]
