# Generated by Django 5.0.7 on 2025-04-12 13:34

import imagekit.models.fields
import recipes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_product_total_mealtimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=recipes.models.image_path),
        ),
    ]
