# Generated by Django 5.0.7 on 2025-04-12 13:42

from django.db import migrations

def set_unknown_as_parent(apps, schema_editor):
    Category = apps.get_model('recipes', 'Category')
    
    # Создаем категорию "unknown" (если её нет)
    unknown_category, created = Category.objects.get_or_create(
        name="unknown",
        defaults={
            'parent_category': None,  # у неё самой нет родителя
            'priority': 0,
        }
    )
    
    # У всех категорий (кроме "unknown") ставим parent_category = unknown_category
    Category.objects.exclude(id=unknown_category.id).update(parent_category=unknown_category)

def reverse_func(apps, schema_editor):
    # При откате миграции убираем parent_category
    Category = apps.get_model('recipes', 'Category')
    Category.objects.update(parent_category=None)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_productimage_image'),
    ]

    operations = [
        migrations.RunPython(set_unknown_as_parent, reverse_func),
    ]
