# Generated by Django 5.0.7 on 2025-04-21 20:31
import os, csv

from django.db import migrations

def import_categories(apps, schema_editor):
    Category = apps.get_model('recipes', 'Category')

    file_path = os.path.join(os.getcwd(), 'recipes', 'migrations', 'data', 'etalon_category.csv')
    

    with open(file_path, 'r', encoding='utf-8') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        next(reader)  # Пропуск заголовка

        for row in reader:
            category_name, parent_name = row
            
            try:
                category = Category.objects.get(name=category_name)
                if parent_name:
                    parent, _ = Category.objects.get_or_create(
                        name=parent_name,
                        defaults={'priority': 0, 'parent_category': None}
                    )
                    category.parent_category = parent
                    category.save()
            except Category.DoesNotExist:
                # Если категории нет - создаем
                parent = None
                if parent_name:
                    parent, _ = Category.objects.get_or_create(
                        name=parent_name,
                        defaults={'priority': 0, 'parent_category': None}
                    )
                Category.objects.create(
                    name=category_name,
                    parent_category=parent,
                    priority=0
                )

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_set_unknown_category_as_parent'),
    ]

    operations = [
        migrations.RunPython(import_categories),
    ]
